---
title: "Flow Cytometry Data"
subtitle: "Nuclei Isolations"
author: "TS O'Leary"
date: "September 27, 2022"
output:
  rmarkdown::html_document:
    theme: sandstone
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
# don't show echos, warnings, or messages
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE,
                      comment = "")
```


# Start analysis

```{r}
# Load packages
require(tidyverse)
require(flowCore)
require(ggcyto)
```

```{r}
# Load data
fs <- read.flowSet(path = here::here("flow/data"),
                    alter.names = TRUE)
```


```{r}
# Structure of flowSet data
str(fs)

# Specific sample data
fs@frames$S2_27SEP2022.fcs
```

# Plot data


## Density plot on all channels

```{r, fig.height = 4}
autoplot(fs[[1]])
autoplot(fs[[2]])
autoplot(fs[[3]])
```


## Denisty plots

### Unscaled

```{r, fig.height = 9}
ggcyto(fs,
       aes(x = B2.A)) +
  geom_density() +
  facet_wrap(~ name,
             ncol = 1) + 
  ggcyto_par_set(limits = "instrument")

ggcyto(fs,
       aes(x = SSC.A)) +
  geom_density() +
  facet_wrap(~ name,
             ncol = 1) + 
  ggcyto_par_set(limits = "instrument")
```

### Logicle

```{r, fig.height = 9}
ggcyto(fs,
       aes(x = B2.A)) +
  geom_density() +
  scale_x_logicle() +
  facet_wrap(~ name,
             ncol = 1) + 
  ggcyto_par_set(limits = "instrument")

ggcyto(fs,
       aes(x = SSC.A)) +
  scale_x_logicle() +
  geom_density() +
  facet_wrap(~ name,
             ncol = 1) + 
  ggcyto_par_set(limits = "instrument")
```


## Size and granularity

- FSC -- relative size

- SSC -- relative granularity

```{r, fig.height = 9}
ggcyto(fs,
       aes(y = SSC.A,
           x = FSC.A)) +
  geom_hex(bins = 200) + 
  facet_wrap(~ name,
             ncol = 1) + 
  ggcyto_par_set(limits = "instrument")
```

## 7-AAD data

```{r, fig.height = 5}
ggcyto(fs[[1]],
       aes(x = B2.A,
           y = SSC.A)) +
  geom_hex(bins = 200) + 
  ggcyto_par_set(limits = "instrument")

ggcyto(fs[[2]],
       aes(x = B2.A,
           y = SSC.A)) +
  geom_hex(bins = 200) + 
  ggcyto_par_set(limits = "instrument")

ggcyto(fs[[3]],
       aes(x = B2.A,
           y = SSC.A)) +
  geom_hex(bins = 200) + 
  ggcyto_par_set(limits = "instrument")
```

### Alternative transformations

```{r, fig.height = 9}
ggcyto(fs[[1]],
       aes(x = B2.A,
           y = SSC.A)) +
  geom_hex(bins = 200) + 
  scale_x_logicle() +
  scale_y_logicle() +
  ggcyto_par_set(limits = "instrument")
```

```{r, fig.height = 9}
ggcyto(fs[[1]],
       aes(x = B2.A,
           y = SSC.A)) +
  geom_hex(bins = 200) + 
  scale_x_flowCore_fasinh() +
  scale_y_flowCore_fasinh() +
  ggcyto_par_set(limits = "instrument")
```

# Gates

## 7-AAD

```{r}
# Create gating set object
gs <- GatingSet(fs)

# Create gate -----

# 7-AAD and SSC cut off
gate_7aad_ssc <- rectangleGate(filterId = "7-AAD High & Low SSC", 
                           "B2.A" = c(25000, Inf),
                           "SSC.A" = c(0, 1e4))

# Large gate
gate_7aad <- rectangleGate(filterId = "7-AAD High", 
                           "B2.A" = c(25000, Inf))

# Add gate to dat
gs_pop_add(gs, gate_7aad_ssc)
gs_pop_add(gs, gate_7aad)

# Recompute
recompute(gs)

# Plot
ggcyto(fs[[2]],
       aes(x = B2.A,
           y = SSC.A),
       subset = "root") +
  geom_hex(bins = 200) +
  geom_gate(gate_7aad_ssc) +
  ggcyto_par_set(limits = "instrument")

ggcyto(fs[[2]],
       aes(x = B2.A,
           y = SSC.A),
       subset = "root") +
  geom_hex(bins = 200) +
  geom_gate(gate_7aad) +
  ggcyto_par_set(limits = "instrument")


# Plot
ggcyto(fs[[3]],
       aes(x = B2.A,
           y = SSC.A),
       subset = "root") +
  geom_hex(bins = 200) +
  geom_gate(gate_7aad_ssc) +
  ggcyto_par_set(limits = "instrument")

ggcyto(fs[[3]],
       aes(x = B2.A,
           y = SSC.A),
       subset = "root") +
  geom_hex(bins = 200) +
  geom_gate(gate_7aad) +
  ggcyto_par_set(limits = "instrument")
```

```{r}
# Count stuff
ps <- gs_pop_get_count_with_meta(gs)

# Details of count
ps %>%
  mutate(percent_of_parent = (Count/ParentCount)*100,
         nuclei_conc = Count/50,
         name = str_remove_all(name, "_27SEP2022.fcs")) %>%
  select(name, Count, ParentCount, Population,
         percent_of_parent, nuclei_conc)
```


## Denisty of nuclei

```{r}
ggcyto(fs[[1]],
       aes(x = B2.A),
       subset = "7-AAD High & Low SSC") +
  geom_density() +
  scale_x_logicle() +
  ggcyto_par_set(limits = "instrument")

ggcyto(fs[[2]],
       aes(x = B2.A),
       subset = "7-AAD High & Low SSC") +
  geom_density() +
  scale_x_logicle() +
  ggcyto_par_set(limits = "instrument")

ggcyto(fs[[3]],
       aes(x = B2.A),
       subset = "7-AAD High & Low SSC") +
  geom_density() +
  scale_x_logicle() +
  ggcyto_par_set(limits = "instrument")
```






