---
title: "Nuclei Concentration Variability"
subtitle: "HEATER Project"
author: "TS O'Leary"
date: 'February 06, 2023'
output:
  rmarkdown::html_document:
    theme: sandstone
    toc: true
    toc_float: true
---



```{r setup, include = FALSE}
# don't show echos, warnings, or messages
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      comment = "")

# Load packages
require(tidyverse)
require(kableExtra)

# Load data
dat <- read_csv(here::here("data/raw/nuclei_counts_2023-02-06.csv")) %>%
  mutate(Slice = str_remove_all(Slice, ".tif")) %>%
  separate(Slice, into = c("sample", "aliquot", "rep"), sep = "_")
```

# Data & Calculations

## Raw data
```{r}
dat
```

## Concentration

```{r}
dat %>%
  mutate(nuc_conc = Count/0.1)
```

## Average Concentration

```{r}
dat %>%
  mutate(nuc_conc = Count/0.1) %>%
  group_by(sample) %>%
  summarise(mean = mean(nuc_conc),
            sd = sd(nuc_conc)) %>%
  summarise(conc = mean(mean),
            sd = sd(mean))
```

### Per sample

```{r}
dat %>%
  mutate(nuc_conc = Count/0.1) %>%
  group_by(sample) %>%
  summarise(mean = mean(nuc_conc),
            sd = sd(nuc_conc))
```

### Per sample aliqout

```{r}
dat %>%
  mutate(nuc_conc = Count/0.1) %>%
  group_by(sample, aliquot) %>%
  summarise(mean = mean(nuc_conc),
            sd = sd(nuc_conc))
```

```{r}
dat %>%
  mutate(nuc_conc = Count/0.1) %>%
  group_by(sample, aliquot) %>%
  summarise(mean = mean(nuc_conc),
            sd = sd(nuc_conc)) %>%
    summarise(conc = mean(mean),
              sd = sd(mean))
```







