---
title: "HEATER: Acclimation Phenotypes"
author: "TS O'Leary"
date: 'February 23, 2023'
output:
  rmarkdown::html_document:
    theme: sandstone
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---



```{r setup, include = FALSE}
# don't show echos, warnings, or messages
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE,
                      comment = "")

# Load packages
require(tidyverse)
require(kableExtra)

# Load data
dat <- read_csv(here::here("data/raw/embryo_acc_pheno.csv"))
dat_new <- read_csv(here::here("data/raw/acclimation_survival_new_geno_summer_2022.csv"))
dat_ph <- read_csv(here::here("data/raw/acclimation_pupation_new_geno_summer_2022.csv"))
dat_ws <- read_csv(here::here("data/raw/acclimation_walking_speed_new_geno_summer_2022.csv"))
```

# Canton S survival

```{r, height = 4, width = 6}
# Plot Canton S survival data
dat %>%
  filter(Genotype == "CantonS") %>%
  filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = Survival*100)) +
  geom_boxplot(width = 0.3,
              color = "grey20",
              outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 3,
                            cex = 2,
                            shape = 21,
                            fill = "grey50",
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Survival after acute heat shock",
                     limits = c(0, 100),
                     labels = function(x) paste0(x, "%")) + 
  theme_classic(base_size = 14) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5))

# Save two sizes
ggsave(here::here("output/figs/cantonS_survival.tiff"), 
       height = 4, width = 6)
ggsave(here::here("output/figs/cantonS_survival_small.tiff"), 
       height = 3.5, width = 5)
```

## All old genotypes

```{r, height = 6, width = 10}
# Plot data for individual genotypes
dat %>% 
  filter(Genotype != "CantonS") %>%
  mutate(Genotype = factor(Genotype, 
                           levels = c("RFM 48", "RFM 6", 
                                      "VT 8", "VT 10", "Chiapas", 
                                       "Ghana", "Guam", "St. Kitts"))) %>%
  mutate(Genotype = recode(Genotype,
         "RFM 48" = "Raleigh, NC, USA (48)",
         "RFM 6" = "Raleigh, NC, USA (6)",
         "VT 8" = "East Calais, VT, USA (8)",
         "VT 10" = "East Calais, VT, USA (10)",
         "Chiapas" = "Chiapas, Mexico",
         "Ghana" = "Ghana, Africa",
         "St. Kitts" = "Monkey Hill, St. Kitts")) %>%
  filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = Survival*100,
             fill = Region)) +
  geom_boxplot(width = 0.3,
               color = "grey20",
               outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 1.5,
                            cex = 2,
                            shape = 21,
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Survival after acute heat shock",
                     limits = c(0, 100),
                     labels = function(x) paste0(x, "%")) + 
  theme_classic(base_size = 14) +
  scale_fill_manual(values = c("skyblue", "pink")) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5)) +
  facet_wrap(~ Genotype,
             nrow = 2)

# Save figure
ggsave(here::here("output/figs/na_genotypes_survival.tiff"), 
       height = 6, width = 10)
```

```{r}
# # Diurnal variation in all these places
# bio <- read_csv("~/R/projects/ox_stress/exp_design/lockwood_lab_stocks_bioclim.csv")
# bio %>%
#   distinct(Locale, .keep_all = TRUE) %>%
#   select(Locale, bio2) %>%
#   mutate(Mean_Diurnal_Range = bio2/10)

# # Analyze results
# mod <- dat %>%
#   filter(Genotype == "CantonS") %>%
#   filter(Temp == 38.75) %>%
#   glm(Survival ~ Acclimation, 
#       weights = Number_Eggs,
#       family = quasibinomial,
#       data = .) 
# 
# summary(mod)
# broom::tidy(mod)
```

# New genotypes

Data that Emily collected in the summer of 2022.

```{r, height = 6, width = 8}
# New genotypes ----------------------------------------------------------------
dat_new %>% 
  mutate(Genotype = factor(Genotype,
                           levels = c("FRMO01", "FRMO02", "JPOK",
                                      "JPSC", "GH169", "GH174"))) %>%
  mutate(Genotype = recode(Genotype,
                           "FRMO01" = "Montpellier, France (1)",
                           "FRMO02" = "Montpellier, France (2)",
                           "JPOK" = "Okinawa, Japan (26°N)",
                           "JPSC" = "Shiojiri, Japan (36°N)",
                           "GH169" = "Accra, Ghana (169)",
                           "GH174" = "Accra, Ghana (174)")) %>%
  dplyr::filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = N_Hatched/N_Eggs*100,
             fill = Region)) +
  geom_boxplot(width = 0.3,
               color = "grey20",
               outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 1.5,
                            cex = 2,
                            shape = 21,
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Survival after acute heat shock",
                     limits = c(0, 100),
                     labels = function(x) paste0(x, "%")) + 
  theme_classic(base_size = 14) +
  scale_fill_manual(values = c("skyblue", "pink")) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5)) +
  facet_wrap(~ Genotype, nrow = 3) 

# Save figure
ggsave(here::here("output/figs/new_genotypes_survival.tiff"), 
       height = 6, width = 8)
```

## Egg-to-pupa survival

```{r, height = 6, width = 8}
# Egg-to-pupa survival
dat_new %>%
  mutate(Genotype = factor(Genotype,
                           levels = c("FRMO01", "FRMO02", "JPOK",
                                      "JPSC", "GH169", "GH174"))) %>%
  mutate(Genotype = recode(Genotype,
                           "FRMO01" = "Montpellier, France (1)",
                           "FRMO02" = "Montpellier, France (2)",
                           "JPOK" = "Okinawa, Japan (26°N)",
                           "JPSC" = "Shiojiri, Japan (36°N)",
                           "GH169" = "Accra, Ghana (169)",
                           "GH174" = "Accra, Ghana (174)")) %>%
  dplyr::filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = N_Pupated/N_Eggs_for_Pupa_Adult*100,
             fill = Region)) +
  geom_boxplot(width = 0.3,
               color = "grey20",
               outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 1.5,
                            cex = 2,
                            shape = 21,
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Egg-to-pupa survival after acute heat shock",
                     limits = c(0, 100),
                     labels = function(x) paste0(x, "%")) + 
  theme_classic(base_size = 14) +
  scale_fill_manual(values = c("skyblue", "pink")) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5)) +
  facet_wrap(~ Genotype, nrow = 3) 

# Save figure
ggsave(here::here("output/figs/new_genotypes_egg_to_pupa.tiff"), 
       height = 6, width = 8)
```

## Egg-to-adult survival

```{r, height = 6, width = 8}
# Egg-to-adult survival
dat_new %>% 
  mutate(Genotype = factor(Genotype,
                           levels = c("FRMO01", "FRMO02", "JPOK",
                                      "JPSC", "GH169", "GH174"))) %>%
  mutate(Genotype = recode(Genotype,
                           "FRMO01" = "Montpellier, France (1)",
                           "FRMO02" = "Montpellier, France (2)",
                           "JPOK" = "Okinawa, Japan (26°N)",
                           "JPSC" = "Shiojiri, Japan (36°N)",
                           "GH169" = "Accra, Ghana (169)",
                           "GH174" = "Accra, Ghana (174)")) %>%
  dplyr::filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = N_Eclosed/N_Eggs_for_Pupa_Adult*100,
             fill = Region)) +
  geom_boxplot(width = 0.3,
               color = "grey20",
               outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 1.5,
                            cex = 2,
                            shape = 21,
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Egg-to-adult survival after acute heat shock",
                     limits = c(0, 100),
                     labels = function(x) paste0(x, "%")) + 
  theme_classic(base_size = 14) +
  scale_fill_manual(values = c("skyblue", "pink")) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5)) +
  facet_wrap(~ Genotype, nrow = 3) 

# Save figure
ggsave(here::here("output/figs/new_genotypes_egg_to_adult.tiff"), 
       height = 6, width = 8)
```

## Pupation height

```{r, height = 6, width = 8}
# Pupation height
dat_ph %>%
  mutate(Genotype = factor(Genotype,
                                levels = c("FRMO01", "FRMO02", "JPOK",
                                           "JPSC", "GH169", "GH174"))) %>%
  mutate(Genotype = recode(Genotype,
                           "FRMO01" = "Montpellier, France (1)",
                           "FRMO02" = "Montpellier, France (2)",
                           "JPOK" = "Okinawa, Japan (26°N)",
                           "JPSC" = "Shiojiri, Japan (36°N)",
                           "GH169" = "Accra, Ghana (169)",
                           "GH174" = "Accra, Ghana (174)")) %>%
  dplyr::filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = Height,
             fill = Region)) +
  geom_boxplot(width = 0.3,
               color = "grey20",
               outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 1.5,
                            cex = 2,
                            shape = 21,
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Pupation height (cm)") +
  theme_classic(base_size = 14) +
  scale_fill_manual(values = c("skyblue", "pink")) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5)) +
  facet_wrap(~ Genotype, nrow = 3) 

# Save figure
ggsave(here::here("output/figs/new_genotypes_pupation_height.tiff"), 
       height = 6, width = 8)
```

## Walking speed

```{r, height = 6, width = 8}
# Walking speed
dat_ws %>%
  mutate(Genotype = factor(Genotype,
                                levels = c("FRMO01", "FRMO02", "JPOK",
                                           "JPSC", "GH169", "GH174"))) %>%
  mutate(Genotype = recode(Genotype,
                           "FRMO01" = "Montpellier, France (1)",
                           "FRMO02" = "Montpellier, France (2)",
                           "JPOK" = "Okinawa, Japan (26°N)",
                           "JPSC" = "Shiojiri, Japan (36°N)",
                           "GH169" = "Accra, Ghana (169)",
                           "GH174" = "Accra, Ghana (174)")) %>%
  dplyr::filter(Stage == "Early") %>%
  mutate(Acclimation = paste0(Acclimation, "°C")) %>%
  ggplot(aes(x = Acclimation,
             y = Speed,
             fill = Region)) +
  geom_boxplot(width = 0.3,
               color = "grey20",
               outlier.shape = NA) +
  ggbeeswarm::geom_beeswarm(size = 1.5,
                            cex = 2,
                            shape = 21,
                            color = "grey20",
                            alpha = 0.9) +
  scale_y_continuous(name = "Walking Speed") +
  theme_classic(base_size = 14) +
  scale_fill_manual(values = c("skyblue", "pink")) +
  labs(x = "Acclimation temperature") +
  theme(axis.line.y = element_line(color = "grey60"),
        axis.line.x = element_line(color = "grey100"),
        axis.ticks = element_line(color = "grey60"),
        panel.grid.major.y = element_line(color = "grey70", 
                                          size = 0.5),
        panel.grid.minor.y = element_line(color = "grey90", 
                                          size = 0.5)) +
  facet_wrap(~ Genotype, nrow = 3) 

# Save figure
ggsave(here::here("output/figs/new_genotypes_walking_speed.tiff", 
                  height = 6, width = 8))
```

# Analysis of acclimation slopes

```{r}
# Plot 
dat %>%
  filter(Genotype == "CantonS") %>%
  filter(Stage == "Early") %>%
  ggplot(aes(x = Acclimation,
                 y = Survival)) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE,
              color = "black",
              linetype = 1)
```


```{r}
# # Linear model
# dat %>%
#   filter(Genotype == "CantonS") %>%
#   filter(Stage == "Early") %>%
#   lm(formula = Survival ~ Acclimation,
#      weights = Number_Eggs,
#      data = .) %>%
#   broom::tidy()
```



```{r}
# Plot for new genotypes
dat_new %>% 
  mutate(Genotype = factor(Genotype,
                           levels = c("FRMO01", "FRMO02", "JPOK",
                                      "JPSC", "GH169", "GH174"))) %>%
  mutate(Genotype = recode(Genotype,
                           "FRMO01" = "Montpellier, France (1)",
                           "FRMO02" = "Montpellier, France (2)",
                           "JPOK" = "Okinawa, Japan (26°N)",
                           "JPSC" = "Shiojiri, Japan (36°N)",
                           "GH169" = "Accra, Ghana (169)",
                           "GH174" = "Accra, Ghana (174)")) %>%
  dplyr::filter(Stage == "Early") %>%
  ggplot(aes(x = Acclimation,
                 y = N_Hatched/N_Eggs)) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE,
              color = "black",
              linetype = 1) +
  facet_wrap(~Genotype)
```

```{r}
# # Linear model for all genotypes
# dat_new %>%
#   group_by(Genotype) %>%
#   nest() %>%
#   mutate(fit = map(data, 
#                    ~lm(N_Hatched/N_Eggs ~ Acclimation, 
#                        weights = N_Eggs, 
#                        data = .))) %>%
#   mutate(tidy = broom::tidy(fit)) 
```

