---
title: "How Embryos Acclimate to Temperature through Epigenetic Regulation"
author: "TS O'Leary"
date: "2023-05-15"
description: "Record of analysis for HEATER project."
output:
  bookdown::gitbook:
    number_sections: true
    split_by: chapter
    toc_depth: 4
    toc_collapse: true
documentclass: book
---

<!-- A quick note to myself about compiling the gitbook. Render this book by using the Knit button in RStudio. When updating the book and knitting again, it may be useful to remove all directories and previous files other than this index.Rmd file. That will avoid saving old files whose sections have been re-named and therefore no longer exist, etc.  -->

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = here::here())
```

# **HEATER** {-}

HEATER Project:

# **Embryonic thermal acclimation**

## Egg hatching success

<!-- If you want to include code but don't want to run it. You may use eval = FALSE in the chunk option. This will print, but not execute the code. -->

```{r, file = "src/00_pheno/cs_pheno_fig.R", eval = FALSE}
```

# **Nuclei isolation**

## Nuclei quality

## Nuclei counts

The data is loaded and then the species are grouped.

```{r, file = "src/00_pheno/cs_pheno_fig.R", eval = FALSE}
```

# **Cell Ranger ARC**

## `mkref`

```{r, file = "src/02_cellranger-arc/00_mkref.sh", eval = FALSE}
```

## `count`

```{r, file = "src/02_cellranger-arc/01_count.sh", eval = FALSE}
```

## `aggr`

```{r, file = "src/02_cellranger-arc/02_aggr.sh", eval = FALSE}
```

# **Seurat**

## Create seurat object

```{r, file = "src/03_seurat/01_create_seurat_object.R", eval = FALSE}
```

## Quality control and filtering

```{r, file = "src/03_seurat/02_quality_control_filtering.R", eval = FALSE}
```

## Clustering

```{r, file = "src/03_seurat/03_cluster.R", eval = FALSE}
```

# Session Info {-}

```{r}
sessionInfo()
```