---
title: "How Embryos Acclimate to Temperature through Epigenetic Regulation"
subtitle: "Scripts"
author: 
  - "Thomas O’Leary, Emily Mikucki, Sumaetee Tangwancharoen, Sara Helms Cahan, Seth Frietze, and Brent L. Lockwood"
output:
  rmarkdown::html_document:
    theme: lumen
    number_sections: true
    toc: true
    toc_float: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)

# Load libraries to record version in Session Info section
library(tidyverse)
library(Seurat)
library(Signac)
library(clustree)
```

# HEATER {-}

## Goals {-}

HEATER Project:

# **Embryonic thermal acclimation**

## Egg hatching success

```{r, file = "src/00_pheno/cs_pheno.R"}
```

<!-- # **Nuclei isolation** -->

<!-- ## Nuclei quality -->

<!-- ## Nuclei counts -->

<!-- The data is loaded and then the species are grouped. -->

<!-- ```{r, file = "src/00_pheno/cs_pheno.R"} -->
<!-- ``` -->

# **Cell Ranger ARC**

## `mkref`

```{r, file = "src/02_cellranger-arc/00_mkref.sh"}
```

## `count`

```{r, file = "src/02_cellranger-arc/01_count.sh"}
```

## `aggr`

```{r, file = "src/02_cellranger-arc/02_aggr.sh"}
```

# **Seurat**

## Create seurat object

```{r, file = "src/03_seurat/00_create_seurat_object.R"}
```

## Quality control and filtering

```{r, file = "src/03_seurat/01_quality_control_filtering.R"}
```

## Initial clustering

```{r, file = "src/03_seurat/02_initial_cluster.R"}
```

## `AMULET` for ATAC doublet id

```{r, file = "src/03_seurat/03_amulet.R"}
```

## `DoubletFinder` for RNA doublet id

```{r, file = "src/03_seurat/04_doublet_finder.R"}
```

## Remove identified multiplets

```{r, file = "src/03_seurat/05_rm_multiplets.R"}
```

# Session Info {-}

```{r, echo = FALSE, eval = TRUE}
sessionInfo()
```
